// <auto-generated />
using System;
using MagicVilla.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231227132917_AgregarDatos")]
    partial class AgregarDatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVillaNetCore.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "Tiene las tremendas Tetas",
                            FechaActualizacion = new DateTime(2023, 12, 27, 10, 29, 17, 435, DateTimeKind.Local).AddTicks(3780),
                            FechaCreacion = new DateTime(2023, 12, 27, 10, 29, 17, 435, DateTimeKind.Local).AddTicks(3740),
                            ImagenUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "Villa Fernanda",
                            Ocupantes = 5,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "Tiene una Cintura y un Culo",
                            FechaActualizacion = new DateTime(2023, 12, 27, 10, 29, 17, 435, DateTimeKind.Local).AddTicks(3790),
                            FechaCreacion = new DateTime(2023, 12, 27, 10, 29, 17, 435, DateTimeKind.Local).AddTicks(3790),
                            ImagenUrl = "",
                            MetrosCuadrados = 70,
                            Nombre = "Villa Maira",
                            Ocupantes = 7,
                            Tarifa = 300.0
                        },
                        new
                        {
                            Id = 3,
                            Amenidad = "",
                            Detalle = "No se a cual de las 2 me Culiaria Primero",
                            FechaActualizacion = new DateTime(2023, 12, 27, 10, 29, 17, 435, DateTimeKind.Local).AddTicks(3790),
                            FechaCreacion = new DateTime(2023, 12, 27, 10, 29, 17, 435, DateTimeKind.Local).AddTicks(3790),
                            ImagenUrl = "",
                            MetrosCuadrados = 100,
                            Nombre = "Villa Fernanda y Maira",
                            Ocupantes = 7,
                            Tarifa = 500.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
